project:
  type: website

website:
  title: "IS415-GAA"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
    left:
      - text: "Hands-on Exercises"
        menu:
          - text: "Hands-on Exercise 01"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
          - text: "Hands-on Exercise 02"
            href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
          - text: "Hands-on Exercise 03 and 04"
            href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html"
          - text: "Hands-on Exercise 05"
            href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05.html"
          - text: "Hands-on Exercise 06"
            href: "Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06.html"
          - text: "Hands-on Exercise 07"
            href: "Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07.html"
      - text: "In-class Exercises"
        menu:
          - text: "In-class Exercise 01"
            href: "In-class_Ex/In-class_Ex01/In_class_Ex01.html"
          - text: "In-class Exercise 02"
            href: "In-class_Ex/In-class_Ex02/In_class_Ex02.html"
          - text: "In-class Exercise 03"
            href: "In-class_Ex/In-class_Ex03/In_class_Ex03.html"
          - text: "In-class Exercise 04"
            href: "In-class_Ex/In-class_Ex04/In_class_Ex04.html"
          - text: "In-class Exercise 05"
            href: "In-class_Ex/In-class_Ex05/In_class_Ex05.html"
          - text: "In-class Exercise 07"
            href: "In-class_Ex/In-class_Ex07/In_class_Ex07.html"
      - text: "Take Home Exercises"
        menu:
          - text: "Take_Home_Exercise 01 Part 1"
            href: "Take_Home_Exercises/Take_Home_Exercise_1/Take_Home_Exercise_01.html"
          - text: "Take_Home_Exercise 01 Part 2"
            href: "Take_Home_Exercises/Take_Home_Exercise_1/Take_Home_Exercise_01P2.html"
          - text: "Take_Home_Exercise 02"
            href: "Take_Home_Exercises/Take_Home_Exercise_2/Take_Home_Exercise_2.html"


format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

