project:
  type: website

website:
  title: "IS415-GAA"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
    left:
      - text: "Hands-on Exercises"
        menu:
          - text: "Hands-on Exercise 01"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
          - text: "Hands-on Exercise 02"
            href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
          - text: "Hands-on Exercise 03 and 04"
            href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html"
          - text: "Hands-on Exercise 05"
            href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05.html"
      - text: "In-class Exercises"
        menu:
          - text: "In-class Exercise 01"
            href: "In-class_Ex/In-class_Ex01/In_class_Ex01.html"
          - text: "In-class Exercise 02"
            href: "In-class_Ex/In-class_Ex02/In_class_Ex02.html"

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

